### ISSUE TITLE
Improve `.gitignore`

### ISSUE THREAD

**Issue by TimboKZ** [ChikamaYan/engs101p-2ndproject-team9#1]
Add `.DS_Store` and the like to your root `.gitignore` file. If y'all are using VS, might be worth checking out [the appropriate `.gitignore` template](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore).

**Comment by ChikaYan** [comment]
!!!!!!?????
Ty but I'm not sure if any external help is allowed for this engineering challenging project
However you are super welcome to check out my cute adorable lovely kawaii [youmu](https://github.com/ChikamaYan/youmu) if you are looking for some codes to shit on
